### ISSUE TITLE
TREND MICRO製ウィルスバスターのWebPageCheckerで画像がぼやける

### ISSUE THREAD

**Issue by oka4shi** [lmGroupJp/modern-css-reset-plus-tool#1]
**This issue is reported by saladbowl77.**

## 内容
TREND MICRO製ウィルスバスターの「Webページ内のリンクの安全性を表示」並びに「マウスポインタを合わせたリンクの安全性を表示」をONにしていると、その画像がぼやける。

## 対処法
```CSS
#UMS_TOOLTIP img,
#TSRToolTipBodyContent img,
#TSRToolTipCloseSpan img,
#TSRToolTipTitle img {
  filter: blur(0px);
}
```
特定のクラスに収納されてるのでそのimgを直接指定し、ぼかしを0にした。

## 追加情報
TREND MICRO製ウィルスバスターの一部表示する。
```HTML
<div id="UMS_TOOLTIP">
 <img id="ums_img_tooltip" class="UMSRatingIcon" src="safari-extension://~/webicon_green.png">
</div>
<!--~~~~~~~~~~~-->
<div id="TSRToolTipCloseSpan">
<div style="background-image:url(safari-extension://~/close_pop.png)" id="TSRToolTipClose"></div>
</div>
<div id="TSRToolTipTitle">
 <img src="safari-extension://~/PC_Icon_Guide_16.png" class="TSRLogoIcon">
<!--~~~~~~~~~~~-->
```
